# Forensic Analysis Lab (containers run tools against read-only evidence)
services:
  # One-stop CLI toolbox (Sleuth Kit, TestDisk/PhotoRec, Foremost, ewf-tools, exiftool, hashdeep, bulk_extractor, YARA, Volatility3)
  # Usage:
  #   Interactive mode (recommended): docker compose run --rm -it dfir
  #   One-off command: docker compose run --rm dfir fls -r /evidence/usb.img
  #   Background mode: docker compose up -d dfir && docker compose exec dfir bash
  dfir:
    build: ./images/dfir-cli
    image: forensic/dfir-cli:latest
    user: "${PUID:-1000}:${PGID:-1000}"
    read_only: true
    working_dir: /cases
    volumes:
      - ./evidence:/evidence:ro    # <-- mount evidence READ-ONLY
      - ./cases:/cases             # outputs & working files
      - ./rules:/rules:ro          # optional YARA rules, etc.
    tmpfs:
      - /tmp
      - /usr/local/lib/python3.13/dist-packages/volatility3/symbols:uid=1000,gid=1000
    stdin_open: true                # Keep STDIN open for interactive sessions
    tty: true                       # Allocate pseudo-TTY for interactive sessions
    # Note: No 'command' specified - uses Dockerfile CMD (/bin/bash) by default

  # Plaso (log2timeline) for super timelines
  plaso:
    image: log2timeline/plaso:latest
    user: "${PUID:-1000}:${PGID:-1000}"
    read_only: true
    working_dir: /cases
    volumes:
      - ./evidence:/evidence:ro
      - ./cases:/cases
    tmpfs:
      - /tmp
    command: ["sleep", "infinity"]

  # Optional GUI: Autopsy over noVNC in your browser at http://localhost:8080/vnc.html
  # Note: community images vary; if it doesn't start on your OS, keep using CLI tools above.
  autopsy:
    image: eecs388/autopsy:latest  # More up-to-date and multi-platform
    depends_on:
      - novnc
    environment:
      - DISPLAY=novnc:0.0
    networks: [x11]
    volumes:
      - ./cases:/cases
      - ./evidence:/evidence:ro
    # Note: No change needed for _JAVA_OPTIONS, but be aware if performance issues arise

  novnc:
    image: theasp/novnc:latest # This image also supports multiple architectures
    ports:
      - "8080:8080"
    environment:
      - DISPLAY_WIDTH=${DISPLAY_WIDTH}
      - DISPLAY_HEIGHT=${DISPLAY_HEIGHT}
      - RUN_XTERM=no
    networks: [x11]

networks:
  x11: {}
